### ISSUE TITLE
디스코드 명령어 파서 개발

### ISSUE THREAD

**Issue by Stdev17** [Stdev17/flip-flop#1]
디스코드 채팅창에서 입력해 온 request를 API의 형태로 파싱할 수 있도록 합니다.

### Phase 1
- [ ] 입력을 정규식 형태로 tokenize
- [x] 입력의 형태와 API 설계의 구상
- [ ] 실존하는 API에 매핑해주는 미들웨어 개발

추후 필요할 경우 reopen하여 보강합니다.
